"""Visualizer tests: pml generation, CGO box, matplotlib fallback."""

from __future__ import annotations

from pathlib import Path

import pytest

from dockflow_core.gridbox import GridBox
from dockflow_core.visualizer import (
    PyMOLRunner,
    _q,
    box_cgo_python_block,
    build_pml_script,
    render_matplotlib,
    split_pdbqt_models,
)


def test_build_pml_script_contents(tmp_path: Path):
    box = GridBox(center=(1, 2, 3), size=(20, 22, 24))
    script = build_pml_script(
        tmp_path / "receptor.pdbqt",
        [tmp_path / "pose1.pdbqt", tmp_path / "pose2.pdbqt"],
        box,
        tmp_path / "render.png",
        session_path=tmp_path / "session.pse",
        affinities=[-9.5, -8.2],
    )
    assert script.startswith("# Auto-generated by DockFlow-Automator")
    assert "receptor.pdbqt, receptor" in script
    assert "pose1.pdbqt, pose_1" in script
    assert "pose2.pdbqt, pose_2" in script
    assert "color [0.85,0.15,0.15], pose_1" in script
    assert "load_cgo" in script
    assert "ray 1600, 1200" in script
    assert "render.png" in script
    assert "session.pse" in script
    assert "cmd.quit()" in script
    assert "-9.50 kcal/mol" in script


def test_build_pml_quotes_paths_with_spaces(tmp_path: Path):
    script = build_pml_script(
        "/tmp/my poses/rec file.pdbqt", ["/tmp/my poses/lig.pdbqt"], None,
        "/tmp/out put.png",
    )
    assert 'load "/tmp/my poses/rec file.pdbqt", receptor' in script
    assert 'png "/tmp/out put.png"' in script
    assert _q("/tmp/a b.pdb") == '"/tmp/a b.pdb"'
    assert _q("/tmp/simple.pdb") == "/tmp/simple.pdb"


def test_box_cgo_python_block():
    import re

    box = GridBox(center=(0, 0, 0), size=(10, 10, 10))
    block = box_cgo_python_block(box, name="mybox")
    assert block.startswith("python\n")
    assert "end python" in block
    assert "cmd.load_cgo" in block
    assert "'mybox'" in block
    # 12 edges * 2 vertices * 3 coordinates = 72 numbers in the VERTEX list
    vertex_section = block.split("[VERTEX]")[1].split("[END]")[0]
    numbers = re.findall(r"-?\d+\.\d+", vertex_section)
    assert len(numbers) == 72


def test_pymol_runner_availability():
    runner = PyMOLRunner()
    assert isinstance(runner.available, bool)
    runner_missing = PyMOLRunner("definitely-not-pymol-xyz")
    assert not runner_missing.available


def test_render_matplotlib_fallback(tmp_path: Path, receptor_pdb_path: Path,
                                    docked_pdbqt_path):
    pytest.importorskip("matplotlib", reason="matplotlib not installed")
    poses = split_pdbqt_models(docked_pdbqt_path, tmp_path / "poses", "pose")
    box = GridBox(center=(12, 10, 8), size=(24, 24, 24))
    out = render_matplotlib(
        receptor_pdb_path, poses[:2], box, tmp_path / "fallback.png",
        affinities=[-9.4, -8.7],
    )
    assert out.is_file()
    assert out.stat().st_size > 5000  # an actual image


def test_render_matplotlib_no_poses(tmp_path: Path, receptor_pdb_path: Path):
    pytest.importorskip("matplotlib", reason="matplotlib not installed")
    out = render_matplotlib(receptor_pdb_path, [], None, tmp_path / "empty.png")
    assert out.is_file()
