"""Visualizer tests: pml generation, CGO box, matplotlib fallback."""

from __future__ import annotations

from pathlib import Path

import pytest

from dockflow_core.gridbox import GridBox
from dockflow_core.visualizer import (
    PyMOLRunner,
    _q,
    box_cgo_python_block,
    build_pml_script,
    render_matplotlib,
    split_pdbqt_models,
)


def test_build_pml_script_contents(tmp_path: Path):
    box = GridBox(center=(1, 2, 3), size=(20, 22, 24))
    script = build_pml_script(
        tmp_path / "receptor.pdbqt",
        [tmp_path / "pose1.pdbqt", tmp_path / "pose2.pdbqt"],
        box,
        tmp_path / "render.png",
        session_path=tmp_path / "session.pse",
        affinities=[-9.5, -8.2],
    )
    assert script.startswith("# Auto-generated by DockFlow-Automator")
    assert "receptor.pdbqt, receptor" in script
    assert "pose1.pdbqt, pose_1" in script
    assert "pose2.pdbqt, pose_2" in script
    assert "color [0.85,0.15,0.15], pose_1" in script
    assert "load_cgo" in script
    assert "ray 1600, 1200" in script
    assert "render.png" in script
    assert "session.pse" in script
    assert "cmd.quit()" in script
    assert "-9.50 kcal/mol" in script


def test_build_pml_quotes_paths_with_spaces(tmp_path: Path):
    script = build_pml_script(
        "/tmp/my poses/rec file.pdbqt", ["/tmp/my poses/lig.pdbqt"], None,
        "/tmp/out put.png",
    )
    assert 'load "/tmp/my poses/rec file.pdbqt", receptor' in script
    assert 'png "/tmp/out put.png"' in script
    assert _q("/tmp/a b.pdb") == '"/tmp/a b.pdb"'
    assert _q("/tmp/simple.pdb") == "/tmp/simple.pdb"


def test_box_cgo_python_block():
    import re

    box = GridBox(center=(0, 0, 0), size=(10, 10, 10))
    block = box_cgo_python_block(box, name="mybox")
    assert block.startswith("python\n")
    assert "end python" in block
    assert "cmd.load_cgo" in block
    assert "'mybox'" in block
    # 12 edges * 2 vertices * 3 coordinates = 72 numbers in the VERTEX list
    vertex_section = block.split("[VERTEX]")[1].split("[END]")[0]
    numbers = re.findall(r"-?\d+\.\d+", vertex_section)
    assert len(numbers) == 72


def test_pymol_runner_availability():
    runner = PyMOLRunner()
    assert isinstance(runner.available, bool)
    runner_missing = PyMOLRunner("definitely-not-pymol-xyz")
    assert not runner_missing.available


def test_render_matplotlib_fallback(tmp_path: Path, receptor_pdb_path: Path,
                                    docked_pdbqt_path):
    pytest.importorskip("matplotlib", reason="matplotlib not installed")
    poses = split_pdbqt_models(docked_pdbqt_path, tmp_path / "poses", "pose")
    box = GridBox(center=(12, 10, 8), size=(24, 24, 24))
    out = render_matplotlib(
        receptor_pdb_path, poses[:2], box, tmp_path / "fallback.png",
        affinities=[-9.4, -8.7],
    )
    assert out.is_file()
    assert out.stat().st_size > 5000  # an actual image


def test_render_matplotlib_no_poses(tmp_path: Path, receptor_pdb_path: Path):
    pytest.importorskip("matplotlib", reason="matplotlib not installed")
    out = render_matplotlib(receptor_pdb_path, [], None, tmp_path / "empty.png")
    assert out.is_file()


# ---------------------------------------------------------------------------
# Visual information smoke test (audit item 33)
# ---------------------------------------------------------------------------
def test_renders_of_distinct_poses_differ_in_pixels(
    tmp_path: Path, receptor_pdb_path: Path, docked_pdbqt_path: Path
):
    """Distinct poses must render to visibly different PNGs.

    The v0.1.1 audit found renders of different ligands/poses with near
    identical byte sizes (~474 KB), suggesting templated output.  This test
    asserts a real pixel difference between two genuinely different pose
    sets so low-information renders fail CI.
    """
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.image as mpimg
        import numpy as np
    except ImportError:  # pragma: no cover
        pytest.skip("matplotlib not installed")

    # pose set A: the docked fixture as-is
    poses_a = tmp_path / "a_out.pdbqt"
    poses_a.write_text(docked_pdbqt_path.read_text(encoding="utf-8"), encoding="utf-8")
    # pose set B: same atoms, but translated by 8 A -> a disjoint pose
    text = poses_a.read_text(encoding="utf-8")
    shifted_lines = []
    for line in text.splitlines():
        if line.startswith(("ATOM", "HETATM")):
            x = float(line[30:38]) + 8.0
            shifted_lines.append(line[:30] + f"{x:8.3f}" + line[38:])
        else:
            shifted_lines.append(line)
    poses_b = tmp_path / "b_out.pdbqt"
    poses_b.write_text("\n".join(shifted_lines) + "\n", encoding="utf-8")

    image_a = tmp_path / "render_a.png"
    image_b = tmp_path / "render_b.png"
    box = GridBox(center=(12.5, 9.7, 8.4), size=(16, 16, 16))
    render_matplotlib(receptor_pdb_path, [poses_a], box, image_a, affinities=[-9.4])
    render_matplotlib(receptor_pdb_path, [poses_b], box, image_b, affinities=[-9.4])
    assert image_a.is_file() and image_b.is_file()

    pixels_a = mpimg.imread(image_a).astype(float)
    pixels_b = mpimg.imread(image_b).astype(float)
    assert pixels_a.shape == pixels_b.shape
    changed = float((np.abs(pixels_a - pixels_b) > 1.0 / 255.0).mean())
    # an 8 A disjoint translation of the whole ligand must change a
    # measurable fraction of pixels (observed on the mini fixture: ~0.1%;
    # on real receptors: >1%; threshold an order of magnitude below)
    assert changed > 2e-4, f"renders are near-identical ({changed:.2%} pixels)"


# -- interactive 3D viewer (peer item 20) ------------------------------------
def _manifest_run(tmp_path, poses=2):
    """Minimal completed-run directory for the viewer generator."""
    import json as json_mod

    (tmp_path / "prepared").mkdir(parents=True, exist_ok=True)
    (tmp_path / "docking").mkdir(parents=True, exist_ok=True)
    (tmp_path / "raw").mkdir(parents=True, exist_ok=True)
    receptor = tmp_path / "prepared" / "receptor.pdbqt"
    receptor.write_text(
        "ATOM      1  CA  ASP A  25       1.000   2.000   3.000"
        "  1.00  0.00     0.100 C\nEND\n", encoding="utf-8")
    pose_text = "MODEL     1\n" + "".join(
        f"ATOM      {i}  C   LIG A   1      {i * 0.5:.3f}   0.000   0.000"
        "  1.00  0.00     0.100 C\n" for i in range(1, 4)) + "ENDMDL\n"
    out = tmp_path / "docking" / "lig1_out.pdbqt"
    out.write_text(pose_text * poses, encoding="utf-8")
    manifest = {
        "run_id": "test_run",
        "receptor": {"pdbqt": str(receptor), "engine": "test"},
        "gridbox": {"center": [0, 0, 0], "size": [20, 20, 20],
                    "source": "ligand:XK2"},
        "docking": {"backend": "test", "results": [{
            "ligand_name": "lig1",
            "poses": [{"model": 1, "affinity": -9.5, "crystal_rmsd": 1.2},
                      {"model": 2, "affinity": -8.1, "crystal_rmsd": 2.4}],
        }]},
        "analysis": {"poses": {"lig1": [{
            "pose_index": 1,
            "residues": [{"chain": "A", "resname": "ASP", "resseq": 25,
                          "geom_hbond_contacts": 2,
                          "hydrophobic_contacts": 1,
                          "ionic_contacts": 0, "metal_contacts": 0,
                          "closest": 3.1}],
        }]}},
        "paths": {},
    }
    (tmp_path / "manifest.json").write_text(
        json_mod.dumps(manifest), encoding="utf-8")
    return tmp_path


def test_interactive_viewer_html_generated(tmp_path):
    from dockflow_core.interactive_viewer import build_interactive_html

    path = build_interactive_html(_manifest_run(tmp_path))
    assert path is not None and path.is_file()
    text = path.read_text(encoding="utf-8")
    assert "3Dmol" in text
    # gridbox coords are serialised as rounded floats ([0.0, 0.0, 0.0])
    assert '"center": [0.0, 0.0, 0.0]' in text
    assert "lig1" in text
    import json as json_mod

    start = text.index("const DATA = ") + len("const DATA = ")
    data, _ = json_mod.JSONDecoder().raw_decode(text[start:])
    assert len(data["poses"]) == 2
    assert data["contacts"] and data["contacts"][0]["resname"] == "ASP"


def test_interactive_viewer_skips_incomplete_runs(tmp_path):
    from dockflow_core.interactive_viewer import build_interactive_html

    assert build_interactive_html(tmp_path) is None  # no manifest
