"""3D visualization through the open-source PyMOL API.

Two rendering paths:

* **PyMOL** (preferred): a ``.pml`` script is generated (pure string
  building, fully testable), then executed either

  - in a subprocess: ``pymol -cq script.pml`` (most robust), or
  - in-process: ``pymol.finish_launching(['pymol', '-cq'])`` + ``cmd.do``.

  Products: ray-traced PNG, a ``.pse`` session, a CGO wire-frame grid box
  and per-pose colouring by rank/affinity.

* **matplotlib fallback** for machines without PyMOL (CI, minimal installs):
  a static 3D scatter of receptor + poses + box rendered through
  ``mpl_toolkits.mplot3d``.

The generated ``.pse`` sessions can be opened interactively with
:func:`open_session` (launches the PyMOL GUI).
"""

from __future__ import annotations

import subprocess
from collections.abc import Sequence
from pathlib import Path

from .gridbox import GridBox
from .pdbio import parse_pdb, split_pdbqt_models
from .utils import DockFlowError, get_logger, which

logger = get_logger("visualizer")

__all__ = [
    "VisualizationError",
    "build_pml_script",
    "box_cgo_python_block",
    "PyMOLRunner",
    "render_complex",
    "render_matplotlib",
    "open_session",
    "render_best_poses",
]


class VisualizationError(DockFlowError):
    """Rendering failed."""


# ---------------------------------------------------------------------------
# PyMOL script generation (pure functions, unit-testable)
# ---------------------------------------------------------------------------
_POSE_COLORS = [
    "0.85,0.15,0.15",  # red    (best)
    "0.95,0.55,0.10",  # orange
    "0.90,0.80,0.10",  # yellow
    "0.30,0.75,0.30",  # green
    "0.25,0.55,0.95",  # blue
    "0.60,0.30,0.85",  # violet
]


def _q(path: str | Path) -> str:
    """Quote a path for the PyMOL scripting language."""
    text = str(path).replace("\\", "/")
    if " " in text or "(" in text or ")" in text:
        return f'"{text}"'
    return text


def box_cgo_python_block(box: GridBox, name: str = "gridbox") -> str:
    """Build a PyMOL python block drawing the box as CGO lines."""
    lo = box.min_corner
    hi = box.max_corner
    corners = [
        (lo[0], lo[1], lo[2]), (hi[0], lo[1], lo[2]),
        (hi[0], hi[1], lo[2]), (lo[0], hi[1], lo[2]),
        (lo[0], lo[1], hi[2]), (hi[0], lo[1], hi[2]),
        (hi[0], hi[1], hi[2]), (lo[0], hi[1], hi[2]),
    ]
    edges = [
        (0, 1), (1, 2), (2, 3), (3, 0),
        (4, 5), (5, 6), (6, 7), (7, 4),
        (0, 4), (1, 5), (2, 6), (3, 7),
    ]
    vertices: list[float] = []
    for a, b in edges:
        for corner in (corners[a], corners[b]):
            vertices.extend(float(v) for v in corner)
    vertex_str = ",".join(f"{v:.3f}" for v in vertices)
    return (
        "python\n"
        "from pymol.cgo import COLOR, BEGIN, LINES, END, VERTEX\n"
        f"box_cgo = [COLOR, 0.20, 0.40, 0.90, BEGIN, LINES]\n"
        f"box_cgo += [VERTEX]\n"
        f"box_cgo += [{vertex_str}]\n"
        "box_cgo += [END]\n"
        f"cmd.load_cgo(box_cgo, {name!r})\n"
        "end python\n"
    )


def build_pml_script(
    receptor_path: str | Path,
    pose_paths: Sequence[str | Path],
    box: GridBox | None,
    out_png: str | Path,
    session_path: str | Path | None = None,
    affinities: Sequence[float | None] | None = None,
    receptor_name: str = "receptor",
    width: int = 1600,
    height: int = 1200,
) -> str:
    """Generate a complete .pml render script.

    Args:
        receptor_path: receptor PDBQT/PDB file.
        pose_paths: per-pose PDBQT files (rank order, best first).
        box: optional grid box drawn as a wire-frame.
        out_png: ray-traced output image.
        session_path: where to save the .pse session.
        affinities: optional per-pose affinities shown in labels.
    """
    lines: list[str] = [
        "# Auto-generated by DockFlow-Automator",
        "bg_color white",
        "set ray_opaque_background, off",
        "set ray_trace_mode, 1",
        "set antialias, 2",
        "set surface_quality, 1",
        "set transparency, 0.85",
        "set valence, 0",
        "",
        f"load {_q(receptor_path)}, {receptor_name}",
        "hide everything, " + receptor_name,
        "show cartoon, " + receptor_name,
        "show surface, " + receptor_name,
        "color gray70, " + receptor_name,
        "",
    ]
    for index, pose_path in enumerate(pose_paths):
        object_name = f"pose_{index + 1}"
        color = _POSE_COLORS[index % len(_POSE_COLORS)]
        lines.append(f"load {_q(pose_path)}, {object_name}")
        lines.append(f"hide everything, {object_name}")
        lines.append(f"show sticks, {object_name}")
        lines.append(f"color [{color}], {object_name}")
        if affinities is not None and index < len(affinities) \
                and affinities[index] is not None:
            label = f"pose {index + 1}: {affinities[index]:.2f} kcal/mol"
            lines.append(f"pseudoatom pose_label_{index + 1}, label={label!r}")
        lines.append("")
    if box is not None:
        lines.append(box_cgo_python_block(box))
        lines.append("")
    lines.append("orient")
    lines.append("zoom " + receptor_name + ", complete=1")
    lines.append(f"ray {width}, {height}")
    lines.append(f"png {_q(out_png)}, dpi=200")
    if session_path is not None:
        lines.append(f"save {_q(session_path)}")
    lines.append("cmd.quit()")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# PyMOL execution
# ---------------------------------------------------------------------------
class PyMOLRunner:
    """Runs .pml scripts through PyMOL, headless."""

    def __init__(self, executable: str | None = None) -> None:
        self.executable = which(executable or "pymol")

    @property
    def available(self) -> bool:
        return self.executable is not None

    def run_script(self, script_path: str | Path, timeout: float = 600.0) -> None:
        if not self.available:
            raise VisualizationError("PyMOL executable not found")
        assert self.executable is not None
        cmd = [self.executable, "-cq", str(script_path)]
        logger.info("running PyMOL headless: %s", " ".join(cmd))
        try:
            proc = subprocess.run(  # noqa: S603
                cmd, capture_output=True, text=True, timeout=timeout, check=False
            )
        except subprocess.TimeoutExpired as exc:
            raise VisualizationError(f"PyMOL render timed out after {timeout}s") from exc
        if proc.returncode != 0:
            raise VisualizationError(
                f"PyMOL failed (rc={proc.returncode}): "
                f"{(proc.stderr or proc.stdout)[-600:]}"
            )

    def run_script_inprocess(self, script_text: str) -> None:
        """Execute a .pml script inside the current Python process."""
        try:
            import pymol
            from pymol import cmd  # noqa: F401
        except ImportError as exc:
            raise VisualizationError(
                "PyMOL python module not importable; install pymol-open-source "
                "(conda install -c conda-forge pymol-open-source)"
            ) from exc
        pymol.finish_launching(["pymol", "-cq"])
        for line in script_text.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            try:
                if line == "cmd.quit()":
                    break
                cmd.do(line)
            except Exception as exc:  # noqa: BLE001 - keep going on per-line errors
                logger.debug("pymol cmd.do failed on %r: %s", line, exc)
        try:
            pymol.cmd.quit()
        except Exception:  # noqa: BLE001
            pass


# ---------------------------------------------------------------------------
# High-level rendering API
# ---------------------------------------------------------------------------
def render_complex(
    receptor_path: str | Path,
    ligand_pose_paths: Sequence[str | Path],
    box: GridBox | None,
    out_png: str | Path,
    session_path: str | Path | None = None,
    affinities: Sequence[float | None] | None = None,
    engine: str = "auto",
    pymol_executable: str | None = None,
    timeout: float = 600.0,
) -> Path:
    """Render receptor + poses + box to ``out_png``.

    Uses PyMOL when available (subprocess preferred, in-process fallback),
    otherwise the matplotlib fallback renderer.
    """
    out_png = Path(out_png)
    out_png.parent.mkdir(parents=True, exist_ok=True)
    runner = PyMOLRunner(pymol_executable)
    use_pymol = (engine == "pymol") or (engine == "auto" and runner.available)
    if use_pymol and runner.available:
        script = build_pml_script(
            receptor_path, ligand_pose_paths, box, out_png, session_path,
            affinities=affinities,
        )
        script_path = out_png.with_suffix(".pml")
        script_path.write_text(script, encoding="utf-8")
        try:
            runner.run_script(script_path, timeout=timeout)
            if out_png.is_file():
                return out_png
            logger.warning("PyMOL finished but no PNG produced; trying in-process")
        except VisualizationError as exc:
            logger.warning("PyMOL subprocess failed (%s); trying in-process", exc)
        try:
            runner.run_script_inprocess(script)
        except VisualizationError:
            if engine == "pymol":
                raise
        if out_png.is_file():
            return out_png
        if engine == "pymol":
            raise VisualizationError("PyMOL produced no output PNG")
    return render_matplotlib(
        receptor_path, ligand_pose_paths, box, out_png, affinities=affinities
    )


def render_matplotlib(
    receptor_path: str | Path,
    ligand_pose_paths: Sequence[str | Path],
    box: GridBox | None,
    out_png: str | Path,
    affinities: Sequence[float | None] | None = None,
    receptor_stride: int = 4,
) -> Path:
    """Static fallback renderer (no PyMOL dependency)."""
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise VisualizationError(
            "neither PyMOL nor matplotlib is available for rendering"
        ) from exc
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

    receptor_atoms = [a for a in parse_pdb(receptor_path) if not a.is_hydrogen]
    step = max(1, receptor_stride)
    receptor_atoms = receptor_atoms[::step]
    fig = plt.figure(figsize=(12, 9), constrained_layout=True)
    ax = fig.add_subplot(111, projection="3d")
    if receptor_atoms:
        xs = [a.x for a in receptor_atoms]
        ys = [a.y for a in receptor_atoms]
        zs = [a.z for a in receptor_atoms]
        ax.scatter(xs, ys, zs, s=4, c="#9aa0a6", alpha=0.35, depthshade=True,
                   label="receptor")
    for index, pose_path in enumerate(ligand_pose_paths):
        from .pdbio import parse_pdbqt

        atoms = parse_pdbqt(pose_path).atoms
        if not atoms:
            continue
        color = _POSE_COLORS[index % len(_POSE_COLORS)]
        rgb = tuple(float(v) for v in color.split(","))
        xs = [a.x for a in atoms]
        ys = [a.y for a in atoms]
        zs = [a.z for a in atoms]
        label = f"pose {index + 1}"
        if affinities is not None and index < len(affinities) \
                and affinities[index] is not None:
            label += f" ({affinities[index]:.2f})"
        ax.scatter(xs, ys, zs, s=28, c=[rgb], edgecolors="k", linewidths=0.3,
                   depthshade=True, label=label)
    if box is not None:
        corners = box.corner_points()
        edges = [
            (0, 1), (1, 2), (2, 3), (3, 0),
            (4, 5), (5, 6), (6, 7), (7, 4),
            (0, 4), (1, 5), (2, 6), (3, 7),
        ]
        for a, b in edges:
            ax.plot(
                [corners[a][0], corners[b][0]],
                [corners[a][1], corners[b][1]],
                [corners[a][2], corners[b][2]],
                color="#1a56db", linewidth=1.0, linestyle="--",
            )
        ax.scatter([], [], [], c="#1a56db", marker="s", label="grid box")
    ax.set_xlabel("X (A)")
    ax.set_ylabel("Y (A)")
    ax.set_zlabel("Z (A)")
    ax.set_title("DockFlow-Automator render (matplotlib fallback)")
    ax.legend(loc="upper left", bbox_to_anchor=(1.02, 1.0), fontsize=9)
    try:
        ax.set_box_aspect((1.0, 1.0, 1.0))
    except AttributeError:  # pragma: no cover - very old matplotlib
        pass
    out_png = Path(out_png)
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=180)
    plt.close(fig)
    return out_png


def open_session(session_path: str | Path, pymol_executable: str | None = None) -> None:
    """Open a .pse session in the interactive PyMOL GUI."""
    executable = which(pymol_executable or "pymol")
    if executable is None:
        raise VisualizationError(
            "PyMOL executable not found; install pymol-open-source to open sessions"
        )
    subprocess.Popen([executable, str(session_path)])  # noqa: S603


def render_best_poses(
    receptor_path: str | Path,
    poses_pdbqt: str | Path,
    box: GridBox | None,
    out_dir: str | Path,
    ligand_name: str,
    affinities: Sequence[float | None] | None = None,
    engine: str = "auto",
    session: bool = True,
    top: int = 5,
    pymol_executable: str | None = None,
) -> list[Path]:
    """Split a multi-pose PDBQT and render the top poses.

    Returns the list of produced image paths (PyMOL or matplotlib).
    """
    out_dir = Path(out_dir)
    pose_files = split_pdbqt_models(poses_pdbqt, out_dir, ligand_name)[:top]
    images: list[Path] = []
    for index, pose_file in enumerate(pose_files):
        subset = affinities[index:index + 1] if affinities is not None else None
        out_png = out_dir / f"{ligand_name}_render_{index + 1:02d}.png"
        render_complex(
            receptor_path, [pose_file], box, out_png,
            session_path=out_dir / f"{ligand_name}_session.pse" if session else None,
            affinities=subset,
            engine=engine,
            pymol_executable=pymol_executable,
        )
        images.append(out_png)
    return images
