#!/usr/bin/env python3
"""Generate a slurm array-job template for large DockFlow screens.

Work-order item 22 / ADR-0007: DockFlow does not manage a cluster - it
GENERATES correct job files.  This script writes an ``sbatch`` array
template that:

* splits the ligand library into ``--array`` chunks (one array task =
  one chunk of ``--chunk-size`` ligands),
* runs ``scripts/batch_dock.py`` per task with the SAME receptor, box,
  seed and output directory (the checkpoint file makes tasks
  independent yet resumable),
* writes per-task logs into ``logs/slurm-%A_%a.log``.

The template is TEXT - review it, edit the partition/account/time
placeholders, then ``sbatch dockflow_screen.sbatch``.  Nothing here
talks to a scheduler, so it is testable without slurm (see
tests/test_hpc.py).

Example::

    python scripts/generate_sbatch.py \\
        --receptor runs/hiv1_protease_redocking/prepared/receptor.pdbqt \\
        --ligand-glob "screening/prepared/*.pdbqt" \\
        --center -8.7,15.5,27.9 --size 18,15.5,25 \\
        --chunk-size 500 --array 0-19 \\
        --out dockflow_screen.sbatch
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

TEMPLATE = """\
#!/bin/bash
# DockFlow-Automator slurm array job (generated by scripts/generate_sbatch.py)
# One array task = one chunk of {chunk_size} ligands.
# Edit PARTITION/ACCOUNT/TIME below to match your cluster, then: sbatch {out_name}
#SBATCH --job-name=dockflow-screen
#SBATCH --partition={partition}
#SBATCH --account={account}
#SBATCH --time={time}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --array={array}
#SBATCH --output=logs/slurm-%A_%a.log

set -euo pipefail

# The DockFlow checkout + python environment on THIS cluster:
DOCKFLOW_HOME={dockflow_home}
PYTHON={python}

RECEPTOR={receptor}
LIGAND_SOURCE={ligand_glob}
CENTER={center}
SIZE={size}

# Chunk math: task id $SLURM_ARRAY_TASK_ID selects a contiguous slice.
CHUNK={chunk_size}
FIRST=$(( SLURM_ARRAY_TASK_ID * CHUNK + 1 ))
LAST=$(( FIRST + CHUNK - 1 ))

cd "$DOCKFLOW_HOME"

# Vina is multithreaded (shared memory): one task = one Vina process with
# all assigned cores.  DO NOT also raise --parallel (oversubscription -
# see USER_GUIDE 'Choosing cpu and parallel').
"$PYTHON" scripts/batch_dock.py \\
    --receptor "$RECEPTOR" \\
    {ligand_flag} \\
    --center "$CENTER" \\
    --size "$SIZE" \\
    --exhaustiveness {exhaustiveness} \\
    --seed {seed} \\
    --cpu $SLURM_CPUS_PER_TASK \\
    --parallel 1 \\
    --chunk-size "$CHUNK" \\
    --skip-first $(( FIRST - 1 )) --take "$CHUNK" \\
    --out-dir {out_dir}

echo "task $SLURM_ARRAY_TASK_ID done (ligands $FIRST..$LAST)"
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a slurm array-job template for a DockFlow screen.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--receptor", required=True)
    parser.add_argument("--ligand-glob", required=True,
                        help="quoted glob of ligand PDBQTs, or path to an SDF")
    parser.add_argument("--center", required=True, help="x,y,z")
    parser.add_argument("--size", default="24,24,24", help="x,y,z")
    parser.add_argument("--chunk-size", type=int, default=500)
    parser.add_argument("--array", default="0-9",
                        help="array spec, e.g. 0-19 or 0-99%8 (max concurrent)")
    parser.add_argument("--exhaustiveness", type=int, default=8)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--out", default="dockflow_screen.sbatch")
    parser.add_argument("--out-dir", default="slurm_screen")
    parser.add_argument("--partition", default="general")
    parser.add_argument("--account", default="ACCOUNT_PLACEHOLDER")
    parser.add_argument("--time", default="24:00:00")
    parser.add_argument("--cpus", type=int, default=8)
    parser.add_argument("--mem", default="16G")
    parser.add_argument("--dockflow-home", default=str(
        Path(__file__).resolve().parents[1]))
    parser.add_argument("--python", default=sys.executable or "python3")
    parser.add_argument("--sdf-flags", action="store_true",
                        help="source is an SDF (adds --sdf, prepared per chunk)")
    return parser.parse_args(argv)


def build_template(args: argparse.Namespace) -> str:
    ligand_flag = ('--sdf "$LIGAND_SOURCE"' if args.sdf_flags
                   else '--ligands "$LIGAND_SOURCE"')
    return TEMPLATE.format(
        out_name=Path(args.out).name,
        partition=args.partition,
        account=args.account,
        time=args.time,
        cpus=args.cpus,
        mem=args.mem,
        array=args.array,
        dockflow_home=args.dockflow_home,
        python=args.python,
        receptor=args.receptor,
        ligand_glob=args.ligand_glob,
        ligand_flag=ligand_flag,
        center=args.center,
        size=args.size,
        chunk_size=args.chunk_size,
        exhaustiveness=args.exhaustiveness,
        seed=args.seed,
        out_dir=args.out_dir,
    )


def chunk_count(n_ligands: int, chunk_size: int) -> int:
    """How many array tasks a library of ``n_ligands`` needs."""
    return max(1, math.ceil(n_ligands / max(1, chunk_size)))


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    template = build_template(args)
    Path(args.out).write_text(template, encoding="utf-8")
    tasks = args.array.split(",")[0]
    print(f"template : {args.out}")
    print(f"array    : {args.array} (task 0 = ligands 1..{args.chunk_size}; "
          f"'{tasks}' is the first task id)")
    print("next     : edit PARTITION/ACCOUNT/TIME, then `sbatch "
          f"{Path(args.out).name}`")
    print("notes    : resumable (batch_results.csv checkpoint); "
          "logs/slurm-<job>_<task>.log; Vina is shared-memory parallel - "
          "keep --parallel 1 and give each task all cores")
    return 0


if __name__ == "__main__":
    sys.exit(main())
